export enum ErrorCodes {
  BALANCE_NOT_ENOUGH = 'BALANCE_NOT_ENOUGH',
  INITIAL_BALANCE_MUST_BE_POSITIVE = 'INITIAL_BALANCE_MUST_BE_POSITIVE',
  BALANCE_MUST_BE_VALID_NUMBER = 'BALANCE_MUST_BE_VALID_NUMBER',
}
